import {
  Archive,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowElbowDownLeft,
  ArrowUp,
  Asterisk,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsIn,
  ArrowsOut,
  BookmarkSimple,
  Books,
  BookOpen,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChatCenteredText,
  ChatCircleDots,
  ChatTeardropText,
  Check,
  Circuitry,
  CodeSimple,
  ClockCountdown,
  ClockAfternoon,
  Copy,
  DotsThree,
  DownloadSimple,
  Envelope,
  EnvelopeSimple,
  Eye,
  FileText,
  EnvelopeOpen,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  GlobeHemisphereWest,
  Image as ImageSquare,
  Info,
  Key,
  Keyboard,
  Link,
  ListBullets,
  ListChecks,
  Lock,
  MagnifyingGlass,
  MinusCircle,
  Microphone,
  Moon,
  NotePencil,
  PencilSimpleLine,
  MusicNote,
  Paperclip,
  PaperPlaneRight,
  Play,
  PlugsConnected,
  Plus,
  PushPin,
  PushPinSimple,
  ShareNetwork,
  SidebarSimple,
  Sidebar as SidebarRight,
  SlidersHorizontal,
  Sparkle,
  SpeakerHigh,
  SquaresFour,
  Square,
  Gear,
  Star,
  Stop,
  Sun,
  SunDim,
  Terminal,
  Trash,
  User,
  VideoCamera,
  WarningCircle,
  X,
  Shield,
  ShieldCheck,
  Lightning,
  Brain,
  Palette,
  Stack,
  TextAa,
  Pause,
  CheckCircle,
  DotsSixVertical,
  DotsNine,
  Desktop,
  Mouse,
  Power,
  WifiHigh,
  Quotes,
  AndroidLogo,
  AppleLogo,
  ArrowSquareOut,
  Broadcast,
  CheckSquare,
  Cloud,
  Database,
  DeviceMobile,
  GithubLogo,
  GoogleLogo,
  SpotifyLogo,
  WindowsLogo,
} from '@phosphor-icons/react'

/* One icon set, one stroke weight, one grid.

   The marks used to be hand-drawn paths, and it showed: strokes disagreed by a
   third of a pixel, optical sizes drifted, and every new one was a small act of
   invention. Phosphor is a real family drawn on a 24px grid, so a row of icons
   lines up because the typeface-equivalent says so, not because each path was
   nudged until it looked close.

   The `<Icon name="…">` API is deliberately unchanged: the names describe what
   the thing does in AMETHYST -- `plug`, `spark`, `logs` -- not what the drawing is
   called upstream, so swapping the family again would touch this file only. */

const MARKS = {
  alert: WarningCircle,
  // The spotlight's two error states ask for this name. It was not in the map,
  // so a failed web or video search drew an empty box where the icon should be
  // -- which reads as "no results" rather than "the search failed".
  'alert-triangle': WarningCircle,
  shield: Shield,
  'shield-check': ShieldCheck,
  zap: Lightning,
  lightning: Lightning,
  brain: Brain,
  palette: Palette,
  layers: Stack,
  type: TextAa,
  pause: Pause,
  'check-circle': CheckCircle,
  'arrow-up': ArrowUp,
  'arrow-right': CaretRight,
  up: ArrowUp,
  file: FileText,
  square: Square,
  database: Database,
  'device-mobile': DeviceMobile,
  mobile: DeviceMobile,
  cloud: Cloud,
  broadcast: Broadcast,
  'check-square': CheckSquare,
  todo: CheckSquare,
  google: GoogleLogo,
  'google-logo': GoogleLogo,
  github: GithubLogo,
  'github-logo': GithubLogo,
  android: AndroidLogo,
  'android-logo': AndroidLogo,
  apple: AppleLogo,
  'apple-logo': AppleLogo,
  spotify: SpotifyLogo,
  'spotify-logo': SpotifyLogo,
  microsoft: WindowsLogo,
  windows: WindowsLogo,
  'external-link': ArrowSquareOut,
  'arrow-square-out': ArrowSquareOut,
  'plugs-connected': PlugsConnected,
  /* Four marks were being asked for by name and had no entry, so `Icon`
     returned null and the button around them rendered as a label with a hole
     in it -- "Manage" and "Uninstall" in the connector drawer, the
     jump-to-latest pill in chat, and the pairing glyph in the OAuth sheet. */
  brand: Asterisk,
  down: ArrowDown,
  'minus-circle': MinusCircle,
  settings: Gear,
  archive: Archive,
  back: CaretLeft,
  book: BookOpen,
  books: Books,
  bookmark: BookmarkSimple,
  'caret-down': CaretDown,
  'chevron-down': CaretDown,
  'caret-up': CaretUp,
  'caret-right': CaretRight,
  'chevron-right': CaretRight,
  quote: Quotes,
  quotes: Quotes,
  chat: ChatCenteredText,
  'chat-bubble': ChatCenteredText,
  'chat-dots': ChatCircleDots,
  check: CheckCircle,
  'check-simple': Check,
  chevron: CaretRight,
  clock: ClockAfternoon,
  copy: Copy,
  undo: ArrowCounterClockwise,
  redo: ArrowClockwise,
  branch: GitBranch,
  speaker: SpeakerHigh,
  'read-aloud': SpeakerHigh,
  more: DotsThree,
  cpu: Circuitry,
  dash: Gauge,
  dots: DotsThree,
  edit: PencilSimpleLine,
  compose: PencilSimpleLine,
  'arrow-up-right': ArrowUpRight,
  folder: FolderOpen,
  'dots-six': DotsSixVertical,
  'dots-nine': DotsNine,
  sparkle: Sparkle,
  grid: SquaresFour,
  globe: Globe,
  'globe-west': GlobeHemisphereWest,
  image: ImageSquare,
  info: Info,
  key: Key,
  keyboard: Keyboard,
  layout: SidebarRight,
  link: Link,
  list: ListBullets,
  lock: Lock,
  logs: ListChecks,
  moon: Moon,
  mail: EnvelopeSimple,
  'mail-open': EnvelopeOpen,
  eye: Eye,
  code: CodeSimple,
  expand: ArrowsOut,
  collapse: ArrowsIn,
  download: DownloadSimple,
  page: FileText,
  paperclip: Paperclip,
  pin: PushPinSimple,
  play: Play,
  music: MusicNote,
  mic: Microphone,
  microphone: Microphone,
  plug: PlugsConnected,
  plus: Plus,
  refresh: ArrowsClockwise,
  search: MagnifyingGlass,
  send: PaperPlaneRight,
  share: ShareNetwork,
  sidebar: SidebarSimple,
  sliders: SlidersHorizontal,
  spark: Sparkle,
  star: Star,
  stop: Stop,
  sun: SunDim,
  term: Terminal,
  trash: Trash,
  user: User,
  camera: Camera,
  monitor: Desktop,
  desktop: Desktop,
  mouse: Mouse,
  power: Power,
  wifi: WifiHigh,
  video: VideoCamera,
  wrap: ArrowElbowDownLeft,
  x: X,
}

/* Optical weight.

   A stroke that is right at 14px is heavy at 28px, because Phosphor's weights
   are a fixed fraction of the 256-unit grid rather than a fixed number of
   device pixels. The old file pinned everything to `regular` and the result
   is what "I don't like the icons" usually means: marks in a 13px status row
   and marks in a 32px empty-state illustration drawn with visibly different
   optical density, so no size looked deliberate.

   Below 20px `regular` is the floor -- `light` at 14px disappears into a
   hairline on a light ground. At 20px and up `light` is correct, and it is
   also what the reference set uses at display sizes.

   `filled` exists for one job: the selected item in a navigation list. An
   outline mark that gains a fill on selection is the cheapest unambiguous
   "you are here" there is, and it survives being read at a glance, in
   greyscale, and by someone who cannot tell the accent colour from the text
   colour. */
export default function Icon({ name, size = 18, weight, filled = false, ...rest }) {
  const Mark = MARKS[name]
  if (!Mark) {
    // A missing mark used to render as nothing, which turns an icon-only
    // button into an invisible hit target. Loud in development, silent and
    // space-holding in production, so the row does not reflow.
    if (import.meta.env?.DEV) console.warn(`Icon: no mark named "${name}"`)
    return <span aria-hidden="true" style={{ display: 'inline-block', width: size, height: size }} />
  }
  const w = weight ?? (filled ? 'fill' : 'regular')
  return <Mark size={size} weight={w} aria-hidden="true" {...rest} />
}
